"""empty message

Revision ID: 4958d160b7ce
Revises: 8a94c7daec3b
Create Date: 2022-01-12 11:57:59.680496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4958d160b7ce'
down_revision = '8a94c7daec3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('resource', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'resource')
    # ### end Alembic commands ###
